# Generated by Django 5.2.11 on 2026-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goal_task_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
    ]
