# Generated by Django 5.1.2 on 2026-01-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя пользователя', max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли пользователь', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последней активности', verbose_name='Last Activity'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия пользователя', max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время регистрации пользователя', verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram', unique=True, verbose_name='Telegram User ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, help_text='Имя пользователя в Telegram (без @)', max_length=255, null=True, verbose_name='Telegram Username'),
        ),
    ]
