# Generated by Django 5.2.9 on 2025-12-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='author',
        ),
    ]
